import React, { useEffect, useState } from 'react';
import Box from '@mui/material/Box';
import Main from 'layouts/Main';
import Container from 'components/Container';
import { useNavigate, useParams } from 'react-router-dom';
import axios from 'axios';
import { Card, Stack } from '@mui/material';
import Typography from '@mui/material/Typography';
import Grid from '@mui/material/Grid';
import { getQRCode } from './qrCode';
import { isMobile } from 'react-device-detect';
import Link from '@mui/material/Link';
import { getBaseUrl } from '../../global';
import { Pass } from './pass';

function obfuscateEmail(email: string): string {
  const [username, domain] = email.split('@');
  if (!username || !domain) {
    return 'unknown';
  }

  const obfuscateCount = Math.floor(username.length / 2);
  const obfuscatedUsername =
    username.slice(0, username.length - obfuscateCount) +
    '*'.repeat(obfuscateCount);

  return `${obfuscatedUsername}@${domain}`;
}

const PassPage = (): JSX.Element => {
  const baseUrl = getBaseUrl();
  const navigate = useNavigate();
  const { id } = useParams();
  if (!id) {
    // redirect to 404
    navigate('/not-found');
  }

  const [pkPass, setPkPass] = useState<string>('');
  const [qr, setQr] = useState<string>('');
  const [pass, setPass] = useState<Pass>(null);
  useEffect(() => {
    if (id) {
      axios
        .get(`${baseUrl}/api/v1/pass/${id}`)
        .then(response => {
          const currentPass: Pass = response.data;

          const pkPass =
            'https://s3.amazonaws.com/wallet-passes.xyz/' +
            currentPass.file_reference;

          const safeCurrent =
            window.location.protocol +
            '//' +
            window.location.host +
            '/pass/' +
            currentPass.id;

          setPass(currentPass);
          if (!isMobile) {
            setQr(getQRCode(safeCurrent));
          } else {
            setPkPass(pkPass);
          }
        })
        .catch(error => {
          console.error(error);
          navigate('/error');
        });
    }
  }, [id, setQr]);

  return (
    <Main>
      <Box bgcolor={'primary.grey'}>
        <Container>
          {pass && (
            <Grid
              item
              xs={12}
              sm={4}
              display={'flex'}
              justifyContent={'center'}
            >
              <Card
                sx={{
                  p: { xs: 2, md: 4 },
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                  maxWidth: 360,
                  width: 1,
                  height: 1,
                  background: 'transparent'
                }}
              >
                {pkPass && (
                  <Stack spacing={2} width={1} alignItems={'center'}>
                    <Box>
                      <Typography
                        color={'text.primary'}
                        variant={'subtitle2'}
                        textAlign={'center'}
                      >
                        This Wallet Pass was generated by{' '}
                        {obfuscateEmail(pass.customer_email)} through ChatGPT on
                        the{' '}
                        <b>
                          {new Date(pass.created_at * 1000).toLocaleString()}
                        </b>
                        .
                      </Typography>
                    </Box>
                    <Box
                      display={'flex'}
                      justifyContent={'center'}
                      alignItems={'center'}
                      marginTop={2}
                      width={'100%'}
                    >
                      <Link
                        href={pkPass}
                        width={'100%'}
                        sx={{
                          maxWidth: 265
                        }}
                      >
                        <img
                          width={'100%'}
                          src={
                            'https://storage.googleapis.com/walletpasses/add_to_wallet.svg'
                          }
                        />
                      </Link>
                    </Box>
                  </Stack>
                )}
                {qr && (
                  <Stack spacing={2} width={1} alignItems={'center'}>
                    <Box>
                      <Typography
                        color={'text.primary'}
                        variant={'subtitle2'}
                        textAlign={'center'}
                      >
                        Scan the QR code bellow from your device to see the
                        button "Add to Wallet".
                      </Typography>
                    </Box>
                    <Box
                      display={'flex'}
                      justifyContent={'center'}
                      alignItems={'center'}
                      marginTop={2}
                    >
                      <img width={'100%'} src={qr} />
                    </Box>
                  </Stack>
                )}
                <Box flexGrow={1} />
                <Stack
                  spacing={2}
                  marginTop={2}
                  width={1}
                  alignItems={'center'}
                >
                  <Box
                    display={'flex'}
                    justifyContent={'center'}
                    alignItems={'center'}
                  >
                    {isMobile && (
                      <Typography
                        color={'text.secondary'}
                        variant={'subtitle2'}
                        textAlign={'center'}
                      >
                        Wallet on Apple Watch, iPhone, and iPod touch is where
                        you store and access all your boarding passes, movie
                        tickets, retail coupons, rewards cards, and more. Just
                        tap on the button above, from your device, to add to
                        your Wallet.
                      </Typography>
                    )}
                    {!isMobile && (
                      <Typography
                        color={'text.secondary'}
                        variant={'subtitle2'}
                        textAlign={'center'}
                      >
                        Wallet on Apple Watch, iPhone, and iPod touch is where
                        you store and access all your boarding passes, movie
                        tickets, retail coupons, rewards cards, and more.
                      </Typography>
                    )}
                  </Box>
                </Stack>
              </Card>
            </Grid>
          )}
        </Container>
      </Box>
    </Main>
  );
};

export default PassPage;
